version: '3.8'

services:

  db:
    image: postgres:12
    restart: always
    volumes:
      - ~/opt/local/local_docker_volume:/var/lib/postgresql/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db


